/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT HW8_KoleHey_BradWard.cdb */

/*  Include Header File  */
#include "HW8_KoleHey_BradWardcfg.h"

/*  Config Structures */
/*  Handles  */
